/**
 * gen-map.mjs — one-off generator for the distribution map geometry.
 *
 * Pulls real Natural Earth country outlines (via world-atlas), projects them,
 * and writes src/components/decor/mapData.ts with embeddable SVG path strings
 * and projected pin coordinates. Run once; the app has no runtime d3 dependency
 * (the generated mapData.ts is committed, so these deps aren't normally installed).
 *
 *   npm i -D d3-geo topojson-client world-atlas   # only needed to regenerate
 *   node scripts/gen-map.mjs
 *
 * Layout (viewBox 1000 x 760):
 *   - Mainland U.S. (lower 48) + the Caribbean share ONE Mercator projection,
 *     so they sit in their true relative positions.
 *   - Hawaii is drawn as a separate, larger-scale INSET box (the standard
 *     cartographic convention, since true-scale Hawaii would be a far-left speck).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { feature } from 'topojson-client'
import { geoMercator, geoPath, geoCentroid } from 'd3-geo'

const VIEW = { w: 1000, h: 760 }
const MAIN_EXTENT = [[58, 96], [948, 612]] // box the mainland+caribbean fit into
const INSET = { x: 76, y: 556, w: 178, h: 150 } // Hawaii inset frame

const topo = JSON.parse(readFileSync('node_modules/world-atlas/countries-50m.json', 'utf8'))
const fc = feature(topo, topo.objects.countries)
const byId = (id) => fc.features.find((f) => f.id === id)

const polyFeature = (coordinates) => ({ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates } })

// --- Split the USA multipolygon into lower-48 / Hawaii / (drop Alaska) -------
const usa = byId('840')
const usParts = usa.geometry.coordinates.map((coords) => {
  const f = polyFeature(coords)
  const [lon, lat] = geoCentroid(f)
  return { coords, lon, lat }
})
const isAlaska = (p) => p.lat > 50
const isHawaii = (p) => p.lat >= 15 && p.lat < 30 && p.lon < -140
const lower48 = {
  type: 'Feature',
  geometry: { type: 'MultiPolygon', coordinates: usParts.filter((p) => !isAlaska(p) && !isHawaii(p)).map((p) => p.coords) },
}
const hawaii = {
  type: 'Feature',
  geometry: { type: 'MultiPolygon', coordinates: usParts.filter(isHawaii).map((p) => p.coords) },
}

// --- Caribbean: explicit allow-list of recognizable island nations ----------
const CARIB_IDS = [
  '192', // Cuba
  '044', // Bahamas
  '388', // Jamaica
  '332', // Haiti
  '214', // Dominican Republic
  '630', // Puerto Rico
  '780', // Trinidad and Tobago
  '052', // Barbados
]
const caribFeatures = CARIB_IDS.map((id) => byId(id) || byId(String(Number(id)))).filter(Boolean)

// --- Projections ------------------------------------------------------------
const mainFC = { type: 'FeatureCollection', features: [lower48, ...caribFeatures] }
const projMain = geoMercator().fitExtent(MAIN_EXTENT, mainFC)
const pathMain = geoPath(projMain)

const projHi = geoMercator().fitExtent(
  [[INSET.x + 12, INSET.y + 26], [INSET.x + INSET.w - 12, INSET.y + INSET.h - 14]],
  hawaii,
)
const pathHi = geoPath(projHi)

// round every number in a path string to 1 decimal to shrink output
const round = (s) => s.replace(/-?\d+\.?\d*/g, (n) => String(Math.round(parseFloat(n) * 10) / 10))
const pt = (xy) => ({ x: Math.round(xy[0] * 10) / 10, y: Math.round(xy[1] * 10) / 10 })

const US_PATH = round(pathMain(lower48))
const CARIB_PATHS = caribFeatures.map((f) => round(pathMain(f)))
const HAWAII_PATH = round(pathHi(hawaii))

// Pins
const US_HUB = pt(projMain([-96, 39])) // central mainland
const CARIB_PIN = pt(projMain([-72.5, 19.4])) // over Hispaniola
const HAWAII_PIN = pt(projHi([-157.9, 21.3])) // Oahu, inside the inset

// graticule reference points (for labelled lat lines), projected
const gridLat = [50, 40, 30, 20].map((lat) => Math.round(projMain([-96, lat])[1] * 10) / 10)
const gridLon = [-120, -100, -80, -60].map((lon) => Math.round(projMain([lon, 30])[0] * 10) / 10)

const out = `// AUTO-GENERATED by scripts/gen-map.mjs — do not edit by hand.
// Real Natural Earth geometry (world-atlas / countries-50m), Mercator-projected.
// viewBox ${VIEW.w} x ${VIEW.h}. Mainland + Caribbean share one projection;
// Hawaii is a separate inset (standard U.S.-map convention).

export const VIEW = { w: ${VIEW.w}, h: ${VIEW.h} } as const
export const INSET = { x: ${INSET.x}, y: ${INSET.y}, w: ${INSET.w}, h: ${INSET.h} } as const

export const US_PATH = ${JSON.stringify(US_PATH)}
export const CARIB_PATHS: string[] = ${JSON.stringify(CARIB_PATHS, null, 0)}
export const HAWAII_PATH = ${JSON.stringify(HAWAII_PATH)}

export const US_HUB = { x: ${US_HUB.x}, y: ${US_HUB.y} } as const
export const CARIB_PIN = { x: ${CARIB_PIN.x}, y: ${CARIB_PIN.y} } as const
export const HAWAII_PIN = { x: ${HAWAII_PIN.x}, y: ${HAWAII_PIN.y} } as const

export const GRID_LAT = ${JSON.stringify(gridLat)}
export const GRID_LON = ${JSON.stringify(gridLon)}
`

mkdirSync('src/components/decor', { recursive: true })
writeFileSync('src/components/decor/mapData.ts', out)

console.log('US_PATH bytes        :', US_PATH.length)
console.log('CARIB_PATHS count    :', CARIB_PATHS.length, '/ bytes', CARIB_PATHS.join('').length)
console.log('HAWAII_PATH bytes    :', HAWAII_PATH.length)
console.log('US_HUB               :', US_HUB)
console.log('CARIB_PIN            :', CARIB_PIN)
console.log('HAWAII_PIN           :', HAWAII_PIN)
console.log('GRID_LAT             :', gridLat)
console.log('GRID_LON             :', gridLon)
console.log('wrote src/components/decor/mapData.ts (', out.length, 'bytes )')
